export const ACTION_TYPES = {
    GET_LISTINGS : 'GET_LISTINGS',
    LISTING_LOADING : "LISTING_LOADING",
    LISTING_FAILED : 'LISTiIG_FAILED',

    GET_USERS : 'GET_USERS',
    USER_LOADING : "USER_LOADING",
    USER_FAILED : 'USER_FAILED',

    GET_SERVICES : 'GET_SERVICES',
    SERVICE_LOADING : "SERVICE_LOADING",
    SERVICE_FAILED : 'SERVICE_FAILED',

    GET_TESTIMONIALS : 'GET_TESTIMONIALS',
    TESTIMONIAL_LOADING : "TESTIMONIAL_LOADING",
    TESTIMONIAL_FAILED : 'TESTIMONIAL_FAILED',

}